### ISSUE TITLE
Nuxtfire ssr mode service worker folder

### ISSUE THREAD

**Issue by magpiedigital** [nuxt-community/firebase-module#199] opened 2020-05-10 10:00 UTC
### Is your feature request related to a problem? Please describe.
At the moment, when you hit npm run dev, the firebase-auth-sw.js gets inserted into the static folder, in the working directory, which interferes with my dev environment. e.g. linters.

### Describe the solution you'd like
Wouldn't it make sense if it was built into dist instead?

**Comment by lupas** [comment] 2020-05-10 10:07
@magpiedigital 
Thanks for submitting this, I'll have a look if that can be done.

Until that's implemented you could add `*.sw` to your `.eslintignore` file (and also `.gitignore` if you're on it), that should get rid of the warning.

**Comment by magpiedigital** [comment] 2020-05-10 10:10
Aye, I have it in my lint ignorePatterns config, so it's not urgent, but I figured it would be more correct to remove it from working dir anyway.

Cheers for this package by the way! You've done a great job

**Comment by lupas** [comment] 2020-06-07 17:22
Hey @magpiedigital 

I had a look at this today.

Nuxt/pwa-module is doing it as we do, by copying the `sw.js`file to the static folder.

I changed the script to copy it to the `/dist` folder like so, which works for publishing, but here the problem is that for local dev the dev-server can't find the files anymore.

```js
      fileName: resolve(
        this.options.srcDir,
        'dist',
        'firebase-auth-sw.js'
      ),
```

Imho I never run into any issues by having the files in the static folder (with .gitingore), do you think this is really necessary?

And if so, any idea on how to approach it better?

**Comment by magpiedigital** [comment] 2020-06-07 17:36
You know more about this than me i'm sure. It just felt weird, but you're right the pwa-module does the same.
It's not really a problem with .gitignore :)

**Comment by lupas** [comment] 2020-06-07 17:37
Haha alright ;-) closing it for now - and if a simple solution comes my way I might think about implementing it :) Thanks!

**Closed by lupas** 2020-06-07 17:37 UTC
