### ISSUE TITLE
auth.addAuthTokenListener is not a function

### ISSUE THREAD

**Issue by uppergoal** [nuxt-community/firebase-module#553] opened 2021-06-16 20:25 UTC
### Version
"@nuxtjs/firebase": "^7.6.1",
"firebase": "^8.6.7",
"nuxt": "^2.15.6",

### Steps to reproduce
in nuxt.config
services: {
      auth: {
        initialize: {
          onAuthStateChangedAction: 'auth/onAuthStateChanged',
        },
        disableEmulatorWarnings: true,
        emulatorHost: isDev && useEmulators ? 'http://localhost' : undefined,
        emulatorPort: isDev && useEmulators ? 9099 : undefined,
      },
      firestore: {
        emulatorPort: isDev && useEmulators ? 8080 : undefined,
        emulatorHost: isDev && useEmulators ? 'localhost' : undefined,
      },
      database: {
        emulatorPort: isDev && useEmulators ? 9000 : undefined,
        emulatorHost: isDev && useEmulators ? 'localhost' : undefined,
      },
      messaging: {
        createServiceWorker: true,
        fcmPublicVapidKey: '',
      },
      storage: true,
    },

### What is Expected?
App working

### What is actually happening?
Error: e.auth.addAuthTokenListener is not a function
When I'm removing the services.database, everything works fine

**Comment by lupas** [comment] 2021-06-16 20:32
Duplicate of: https://github.com/nuxt-community/firebase-module/issues/550

> Please downgrade Firebase to "firebase": "8.6.5" and try again, the newest v8.6.7 seemed to have introduced this bug.
> I assume they will fix it in the next update.

**Closed by lupas** 2021-06-16 20:32 UTC

**Comment by uppergoal** [comment] 2021-06-16 21:51
Sorry for the duplicated issue and thanks for your quick reply. The error is still there with firebase v8.6.5
