### ISSUE TITLE
ERROR The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by KazakovKirill** [nuxt-community/firebase-module#125] opened 2020-03-16 21:00 UTC
Hello!
When deploying on zeit now platform (SSR on cloud functions) I'm getting this error:
> [GET] /
>  ERROR  The "path" argument must be of type string. Received type undefined
>   at validateString (internal/validators.js:112:11)
>   at Object.resolve (path.js:980:7)
>   at Object.<anonymous> (server.js:2:1141225)
>   at r (server.js:2:132)
>   at Object.<anonymous> (server.js:2:809837)
>   at r (server.js:2:132)
>   at Object.<anonymous> (server.js:2:809637)
>   at r (server.js:2:132)
>   at Module.<anonymous> (server.js:2:1518943)
>   at r (server.js:2:132)

But I don't have this error when I run it locally in dev mode. But in this case "store.authUser" always empty in nuxt middleware.

Repository with this issue:
[https://github.com/KazakovKirill/firetest.git](https://github.com/KazakovKirill/firetest.git)

**Comment by lupas** [comment] 2020-03-16 21:09
@KazakovKirill 
I don't really know Zeit and in general not really familiar with Cloud Function deployment, but we already experience issues with a deployment on Firebase Cloud Functions ([open issue](https://github.com/nuxt-community/firebase-module/issues/123)). Might be related.

Can you share your @Nuxtjs/Firebase config?

@mentAl-maZe
might this be related to the issue you're having?

**Comment by KazakovKirill** [comment] 2020-03-16 21:17
> @lupas 
Sure, full config here: [nuxt.config.js](https://github.com/KazakovKirill/firetest/blob/master/nuxt.config.js)

```
firebase: {
    config: {
      apiKey: 'xxx',
      authDomain: 'xxx',
      databaseURL: 'xxx',
      projectId: 'xxx',
      storageBucket: 'xxx',
      messagingSenderId: 'xxx',
      appId: 'xxx'
    },
    services: {
      auth: {
        static: true,
        initialize: {
          onAuthStateChangedAction: 'onAuthStateChangedAction'
        },
        ssr: true
      },
      firestore: {
        static: true,
        enablePersistence: true,
        synchronizeTabs: true
      }
    }
  }
```

**Comment by sorxrob** [comment] 2020-03-20 16:18
Did you make it work?

**Comment by mentAl-maZe** [comment] 2020-03-20 16:38
@lupas 
I don't think this is the same issue I'm facing with firebase, although I might run into this once i've figured out how to include the server middleware in the build, which I have not yet found the time to address.

@KazakovKirill 
Thanks for sharing will try over the weekend.

**Comment by sorxrob** [comment] 2020-03-20 16:46
I'm getting this error too.

`"firebase-admin": "^8.10.0"`

running `now dev` gives me 

```
The "path" argument must be of type string. Received type number
    at validateString (internal/validators.js:113:11)
```

My `now.json`

```json
{
  "version": 2,
  "env": {
    "SERVICE_ACCOUNT_KEY": "@service-account-key",
    "DATABASE_URL": "@database-url",
    "TOKEN": "@token"
  },
  "builds": [
    {
      "src": "index.js",
      "use": "@now/node-server"
    }
  ],
  "routes": [
    {
      "src": "/",
      "dest": "/index.js",
      "methods": ["GET"]
    }
  ]
}

```

**Comment by mentAl-maZe** [comment] 2020-03-23 14:56
@KazakovKirill 
I have checked out your repo, here are my takeaways:

I realize this is just an example repo but nevertheless here are

## A few tipps:

- You always use `store.authUser` to reference the state variable
  => this should be `store.state.authUser`
- `asyncData` only get's triggered on the Server side on first page load, therefore resulting in an anonymously logged in user in the backend, conversely no user on the frontend.
  With your current implemetation you have to navigate to a subpage and back, for the user to be logged in, a full page reload will never sign in a user
  => use the mounted life cycle hook to log in the user:
  ```js
  export default {
    // ...
    async mounted() {
      if (!store.state.authUser) await app.$fireAuth.signInAnonymously()
    }
    // ...
  }
  ```
- In your `nuxt.config.js` in the `firebase.services.firestore` setting you define `synchronizeTabs` alongside `enablePersistence`, `synchronizeTabs` is a configuration FOR `enablePersistence`
  => define `synchronizeTabs` inside `enablePersistence` for it to have any effect
  ```js
  // ...
  firebase: {
    // ...
    services: {
      // ...
      firestore: {
        enablePersistence: {
          synchronizeTabs: true
        }
      }
    }
  }
  // ...
  ```
## To you main problem:

The issue is not with this module nor with firebase (well kind of with firebase :thinking: )

The issue seems to only concern `firebase/firestore`, if you do not use `firestore` you do **NOT** need the below workaround.

I have not gone into detail about this but zeit seems to fail to resolve `firebase/firestore` when installed directly via `firebase` > `@firebase/firestore`
To circumvent this issue you have to register **ALL** firebase dependencies as external packages with webpack on the server side of things (see [@nuxtjs/now-builder - issue 41](https://github.com/nuxt/now-builder/issues/41#issuecomment-494717072))

In you `nuxt.config.js`:
```js
export default {
  build: {
    extend(config, { isServer }) {
      if (isServer) {
        config.externals = {
          '@firebase/app': 'commonjs @firebase/app',
          '@firebase/auth': 'commonjs @firebase/auth',
          '@firebase/firestore': 'commonjs @firebase/firestore',
          // ...
        }
      }
    }
  }
}
```

**Comment by mentAl-maZe** [comment] 2020-03-23 14:58
@sorxrob 
Please check if the mentioned workaround solves your problem.

@lupas 
Please close this issue as this is not related to this module

**Comment by lupas** [comment] 2020-03-23 18:12
Closed due to this being a general issue, not specific to this module.

**Closed by lupas** 2020-03-23 18:12 UTC
